# Generated by Django 4.2.4 on 2024-11-04 12:20

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_fa', models.CharField(max_length=300, null=True)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('description_fa', tinymce.models.HTMLField(null=True)),
                ('description_en', tinymce.models.HTMLField(null=True)),
                ('image', models.ImageField(upload_to='industry')),
                ('image_thumbnail', models.ImageField(upload_to='industry/thumbs')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
                ('keywords', models.CharField(max_length=300, null=True)),
                ('keywords_fa', models.CharField(max_length=300, null=True)),
                ('keywords_en', models.CharField(max_length=300, null=True)),
                ('seo_description', models.TextField(null=True)),
                ('seo_description_fa', models.TextField(null=True)),
                ('seo_description_en', models.TextField(null=True)),
            ],
        ),
    ]
