# Generated by Django 4.2.4 on 2024-11-04 10:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_title_en_category_title_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
