# Generated by Django 4.2.4 on 2024-11-04 12:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_fa', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('about', tinymce.models.HTMLField()),
                ('about_fa', tinymce.models.HTMLField(null=True)),
                ('about_en', tinymce.models.HTMLField(null=True)),
                ('mission', tinymce.models.HTMLField()),
                ('mission_fa', tinymce.models.HTMLField(null=True)),
                ('mission_en', tinymce.models.HTMLField(null=True)),
                ('quote', tinymce.models.HTMLField()),
                ('quote_fa', tinymce.models.HTMLField(null=True)),
                ('quote_en', tinymce.models.HTMLField(null=True)),
                ('sub_industries', tinymce.models.HTMLField()),
                ('sub_industries_fa', tinymce.models.HTMLField(null=True)),
                ('sub_industries_en', tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('logo_light', models.ImageField(null=True, upload_to='logo')),
                ('logo_dark', models.ImageField(null=True, upload_to='logo')),
                ('description', models.TextField(null=True)),
                ('description_fa', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('address_fa', models.CharField(max_length=300, null=True)),
                ('address_en', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, null=True)),
                ('icon', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('main_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='home.siteinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('description_fa', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='slider')),
                ('home_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='home.homedata')),
            ],
        ),
        migrations.CreateModel(
            name='HelpfulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('title_fa', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('main_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='home.siteinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('home_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='home.homedata')),
            ],
        ),
    ]
