# Generated by Django 4.2.4 on 2024-01-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_helpfullinks_main_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='description',
        ),
        migrations.RemoveField(
            model_name='features',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='features',
            name='description_fa',
        ),
    ]
