# Generated by Django 4.2.4 on 2024-11-04 10:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_features_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='about_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='about_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='mission',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='mission_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='mission_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='quote',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='quote_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='quote_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='sub_industries',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='sub_industries_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='sub_industries_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
