# Generated by Django 4.2.4 on 2024-11-04 12:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_fa', models.CharField(max_length=300, null=True)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(upload_to='about')),
                ('description', tinymce.models.HTMLField()),
                ('description_fa', tinymce.models.HTMLField(null=True)),
                ('description_en', tinymce.models.HTMLField(null=True)),
                ('keywords', models.CharField(max_length=300, null=True)),
                ('keywords_fa', models.CharField(max_length=300, null=True)),
                ('keywords_en', models.CharField(max_length=300, null=True)),
                ('seo_description', models.TextField(null=True)),
                ('seo_description_fa', models.TextField(null=True)),
                ('seo_description_en', models.TextField(null=True)),
            ],
        ),
    ]
